/*
Copyright 2020 Adam Honse <calcprogrammer1@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

// Backlight configuration
#define BACKLIGHT_LEVELS 8

#define LED_MATRIX_ROWS MATRIX_ROWS
#define LED_MATRIX_ROW_CHANNELS 3
#define LED_MATRIX_ROWS_HW (LED_MATRIX_ROWS * LED_MATRIX_ROW_CHANNELS)
#define LED_MATRIX_ROW_PINS { C0, C1, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, B6, B7, B8, B9, B10, B11 }

#define LED_MATRIX_COLS MATRIX_COLS
#define LED_MATRIX_COL_PINS MATRIX_COL_PINS

// Effects
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

// Additional Effects
#define ENABLE_RGB_MATRIX_ALPHAS_MODS 
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN 
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT 
#define ENABLE_RGB_MATRIX_BREATHING 
#define ENABLE_RGB_MATRIX_BAND_SAT 
#define ENABLE_RGB_MATRIX_BAND_VAL 
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT 
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL 
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT 
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL 
#define ENABLE_RGB_MATRIX_CYCLE_ALL 
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN 
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON 
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN 
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL 
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL 
#define ENABLE_RGB_MATRIX_DUAL_BEACON 
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON 
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS 
#define ENABLE_RGB_MATRIX_RAINDROPS 
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS 
#define ENABLE_RGB_MATRIX_HUE_BREATHING 
#define ENABLE_RGB_MATRIX_HUE_PENDULUM 
#define ENABLE_RGB_MATRIX_HUE_WAVE 
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL 
#define ENABLE_RGB_MATRIX_PIXEL_FLOW 
#define ENABLE_RGB_MATRIX_PIXEL_RAIN

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYRELEASES
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 50
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS 
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS 
#define ENABLE_RGB_MATRIX_SPLASH 
#define ENABLE_RGB_MATRIX_MULTISPLASH 
#define ENABLE_RGB_MATRIX_SOLID_SPLASH 
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH 

// END 

#define DRIVER_LED_TOTAL (90)
